// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AccessTokenInput struct {
	Token string `json:"token"`
}

type AuthenticatedUser struct {
	Name        string `json:"name"`
	Email       string `json:"email"`
	AccessToken string `json:"accessToken"`
}

type CartItems struct {
	ItemID    int    `json:"itemID"`
	Name      string `json:"name"`
	Price     int    `json:"price"`
	Quantity  int    `json:"quantity"`
	ImagePath string `json:"imagePath"`
}

type CartItemsInput struct {
	ItemID    int    `json:"itemID"`
	Name      string `json:"name"`
	Price     int    `json:"price"`
	Quantity  int    `json:"quantity"`
	ImagePath string `json:"imagePath"`
}

type CustomerCart struct {
	Email     string            `json:"email"`
	EmptyCart bool              `json:"emptyCart"`
	Cart      []*CartItemsInput `json:"cart"`
}

type CustomerDetails struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type CustomerEmailAdd struct {
	Email string `json:"email"`
}

type CustomerEmailInput struct {
	Email string `json:"email"`
}

type CustomerLoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CustomerRegistrationInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type EncryptKey struct {
	Key string `json:"key"`
}

type NewPetDetails struct {
	Name          string `json:"name"`
	Gender        string `json:"gender"`
	Species       string `json:"species"`
	PetBreed      string `json:"petBreed"`
	Age           string `json:"age"`
	Weight        string `json:"weight"`
	HealthConcern string `json:"healthConcern"`
	OwnerEmail    string `json:"ownerEmail"`
}

type PastOrders struct {
	Date       string `json:"date"`
	OrderID    int    `json:"orderID"`
	Store      string `json:"store"`
	Items      int    `json:"items"`
	Total      int    `json:"total"`
	TrackingID string `json:"trackingID"`
	Status     string `json:"status"`
}

type PetDetails struct {
	Name          string `json:"name"`
	Gender        string `json:"gender"`
	Species       string `json:"species"`
	PetBreed      string `json:"petBreed"`
	Age           string `json:"age"`
	Weight        string `json:"weight"`
	HealthConcern string `json:"healthConcern"`
	OwnerEmail    string `json:"ownerEmail"`
}

type ProductList struct {
	ItemID        int    `json:"itemID"`
	Name          string `json:"name"`
	HealthConcern string `json:"healthConcern"`
	Species       string `json:"species"`
	Price         int    `json:"price"`
	Stock         int    `json:"stock"`
	ImagePath     string `json:"imagePath"`
}

type SearchInput struct {
	SearchType    int    `json:"searchType"`
	Species       string `json:"species"`
	HealthConcern string `json:"healthConcern"`
}
